"""empty message

Revision ID: 24d56fd24e25
Revises: 8efc40ab5335
Create Date: 2020-05-01 13:18:19.955516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24d56fd24e25'
down_revision = '8efc40ab5335'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todolists', sa.Column('completed', sa.Boolean(), nullable=True))
    op.execute('UPDATE todolists SET completed=false WHERE completed IS NULL')
    op.alter_column('todolists', 'completed', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todolists', 'completed')
    # ### end Alembic commands ###
